= Notes
Michael Brenner
:toc:

== Problems
=== Speed
* [x] When running over directories with up to 500 GB or more, the program slows down and
grinds to a halt. It lasts long enough for Windows to think that the program has froze and I lose
the ability to click the stop scanning button.
* [x] After the first scan, almost all output to the LogOutput on the GUI stops and no longer updates until the scan completes and goes through the waiting period.

=== Scanning
* [ ] Needs to be able to identify if a file has been removed, re-added(no longer shown as possible
discrepency in window), and then modified.

== Solutions Found
=== Sending data to different threads in PyQt.
* [x] I was able to solve this problem through the use of PyQt's signal and slot system. I was trying to use other, much more complicated methods such as asyncio to get around this, however that way overcomplicated things and didn't actually work. Working with PyQt signal/slot system worked out to be the simplest and most effective solution.
